In [2]:
# 1. 라이브러리 임포트하기
from PublicDataReader import TransactionPrice
import PublicDataReader as pdr

In [3]:

# 2. 공공 데이터 포털 OpenAPI 서비스 인증키 입력하기
service_key = "공공데이터포털에서 발급받은 인코딩 서비스 키"

# 3. 국도교통부 실거래가 정보 조회 OpenAPI 세션 정의하기
# debug : True이면 모든 메세지 출력, False이면 오류 메세지만 출력 (기본값 : False)
api = TransactionPrice(service_key)

In [4]:

# 4. 지역코드(시군구코드) 검색하기
sigungu_name = "분당구" # 시군구코드 : 41135
code = pdr.code_bdong()
code.loc[(code['시군구명'].str.contains(sigungu_name)) &
         (code['읍면동명']=='')]

출처: 행정기관(행정동) 및 관할구역(법정동) 변경내역(2023. 7. 3. 시행)

     시도코드  시도명  시군구코드     시군구명       법정동코드 읍면동명 동리명      생성일자 말소일자
5253   41  경기도  41135  성남시 분당구  4113500000           19910916

In [5]:
# 5. 특정 년월 자료만 조회하기
df = api.get_data(   
    property_type="아파트", # 부동산 상품 종류(아파트, 오피스텔, 단독다가구 등)
    trade_type="매매", # 부동산 거래 유형(매매, 전월세)
    sigungu_code="11650",
    year_month="202212",
)

# 6. 특정 기간 자료 조회하기
df = api.get_data(
    property_type="아파트", # 부동산 상품 종류(아파트, 오피스텔, 단독다가구 등)
    trade_type="매매", # 부동산 거래 유형(매매, 전월세)
    sigungu_code="11650",
    start_year_month="202212",
    end_year_month="202301",
)
    
df.tail()

,지역코드,도로명,법정동,지번,아파트,건축년도,층,전용면적,년,월,...,법정동부번코드,법정동시군구코드,법정동읍면동코드,법정동지번코드,일련번호,거래유형,중개사소재지,해제사유발생일,해제여부,등기일자
78,11650,서운로,서초동,1312-3,롯데캐슬클래식,2006,9,120.18,2023,1,...,0003,11650,10800,1,11650-3300,중개거래,서울 서초구,None,None,23.04.19
79,11650,서운로,서초동,1312-3,롯데캐슬클래식,2006,18,74.30,2023,1,...,0003,11650,10800,1,11650-3300,중개거래,서울 서초구,None,None,23.04.12
80,11650,헌릉로8길,내곡동,NaN,서초포레스타2단지,2015,11,84.87,2023,1,...,0000,11650,10900,1,11650-4156,중개거래,서울 서초구,None,None,23.01.20
81,11650,헌릉로8길,내곡동,411,서초더샵포레,2014,3,101.31,2023,1,...,0000,11650,10900,1,11650-4063,중개거래,서울 서초구,None,None,23.02.24
82,11650,헌릉로8길,내곡동,411,서초더샵포레,2014,12,101.34,2023,1,...,0000,11650,10900,1,11650-4063,중개거래,경기 광주시,23.06.19,O,None